version: '3.8'

services:
  scheduler:
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - WORKER_ROLE=scheduler,reaper
      - WORKER_ID=local-scheduler
    volumes:
      - ./apps/worker/tmp:/app/apps/worker/tmp
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"

  worker:
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - WORKER_ROLE=runner
      - WORKER_ID=local-runner
      - ENABLE_MATCH_RUN=true
    volumes:
      - ./apps/worker/tmp:/app/apps/worker/tmp
    deploy:
      replicas: 6
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"

networks:
  default:
    name: chess-arena-net
