#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
DOTMAX_DIR="${DOTMAX_DIR:-/tmp/dotmax}"
WORK_DIR="$(mktemp -d /tmp/dotmax-live-tuner-XXXXXX)"

cleanup() {
  rm -rf "$WORK_DIR"
}
trap cleanup EXIT

INPUT_IMAGE="${1:-${DOTMAX_TUNE_IMAGE:-$REPO_ROOT/apps/web/public/replay/openai-piece-set/preview_strip.png}}"
if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  cat <<'USAGE'
Usage:
  ./scripts/dotmax_live_tuner.sh [image_path]

Live interactive dotmax tuner (terminal window), then exports final settings for piece generation.

Env options:
  DOTMAX_DIR         Path to dotmax repo (default: /tmp/dotmax)
  DOTMAX_TUNE_IMAGE  Default image if no positional path is passed
  DOTMAX_TUNE_LOG    Where to save tuner session log
  DOTMAX_TUNE_EXPORT Where to save exported env preset
USAGE
  exit 0
fi
if [[ ! -f "$INPUT_IMAGE" ]]; then
  INPUT_IMAGE="$REPO_ROOT/apps/web/public/replay/openai-piece-set/white/01_king.png"
fi

if [[ ! -f "$INPUT_IMAGE" ]]; then
  echo "[dotmax-live-tuner] input image not found"
  echo "Tried: ${1:-<none>} and fallback in openai-piece-set"
  exit 1
fi

if [[ ! -f "$DOTMAX_DIR/Cargo.toml" ]]; then
  echo "[dotmax-live-tuner] dotmax not found at $DOTMAX_DIR"
  echo "[dotmax-live-tuner] cloning https://github.com/newjordan/dotmax ..."
  env GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_NOSYSTEM=1 \
    git clone https://github.com/newjordan/dotmax "$DOTMAX_DIR"
fi

mkdir -p "$WORK_DIR/src"
cp "$DOTMAX_DIR/examples/render_tuner.rs" "$WORK_DIR/src/main.rs"
cat > "$WORK_DIR/Cargo.toml" <<CARGO
[package]
name = "dotmax_live_tuner"
version = "0.1.0"
edition = "2021"

[dependencies]
dotmax = { path = "$DOTMAX_DIR", features = ["image"] }
image = "0.25"
crossterm = "0.29"
CARGO

stamp="$(date +%Y%m%d_%H%M%S)"
LOG_FILE="${DOTMAX_TUNE_LOG:-/tmp/dotmax_tuner_${stamp}.log}"
EXPORT_FILE="${DOTMAX_TUNE_EXPORT:-$REPO_ROOT/scripts/dotmax_piecegen/presets/final_from_tuner.env}"

mkdir -p "$(dirname "$EXPORT_FILE")"

echo "[dotmax-live-tuner] input:  $INPUT_IMAGE"
echo "[dotmax-live-tuner] log:    $LOG_FILE"
echo "[dotmax-live-tuner] export: $EXPORT_FILE"
echo "[dotmax-live-tuner] controls: D/T/arrows/B/b/C/c/G/g/M/R/S/Q"

run_cmd="cargo run --release --manifest-path \"$WORK_DIR/Cargo.toml\" -- \"$INPUT_IMAGE\""

if ! command -v script >/dev/null 2>&1; then
  echo "[dotmax-live-tuner] missing required command: script"
  echo "Install util-linux (or BSD script) and rerun."
  exit 1
fi

run_exit=0
script -q -e -c "$run_cmd" "$LOG_FILE" || run_exit=$?

if [[ "${run_exit:-0}" -ne 0 ]]; then
  echo "[dotmax-live-tuner] tuner exited with non-zero status: $run_exit"
  echo "[dotmax-live-tuner] kept log at: $LOG_FILE"
  exit "$run_exit"
fi

clean_log="$(mktemp /tmp/dotmax_tuner_clean_XXXXXX.log)"
trap 'rm -f "$clean_log"' EXIT

# Strip carriage returns and ANSI escapes.
tr -d '\r' < "$LOG_FILE" \
  | sed -E 's/\x1B\[[0-9;?]*[ -\/]*[@-~]//g' \
  > "$clean_log"

extract_last() {
  local pattern="$1"
  grep -Eo "$pattern" "$clean_log" | tail -n 1 || true
}

dither_raw="$(extract_last 'DitheringMethod::[A-Za-z]+')"
case "$dither_raw" in
  *FloydSteinberg) DM_DITHER="floyd" ;;
  *Bayer) DM_DITHER="bayer" ;;
  *Atkinson) DM_DITHER="atkinson" ;;
  *None) DM_DITHER="none" ;;
  *) DM_DITHER="floyd" ;;
esac

brightness_raw="$(extract_last '\\.brightness\\([0-9.]+\\)\\?')"
contrast_raw="$(extract_last '\\.contrast\\([0-9.]+\\)\\?')"
gamma_raw="$(extract_last '\\.gamma\\([0-9.]+\\)\\?')"
threshold_raw="$(extract_last '\\.threshold\\([0-9]+\\)')"
color_raw="$(extract_last 'ColorMode::(Monochrome|Grayscale|TrueColor)')"

DM_BRIGHTNESS="$(printf '%s' "$brightness_raw" | sed -E 's/.*\\(([0-9.]+)\\).*/\\1/')"
DM_CONTRAST="$(printf '%s' "$contrast_raw" | sed -E 's/.*\\(([0-9.]+)\\).*/\\1/')"
DM_GAMMA="$(printf '%s' "$gamma_raw" | sed -E 's/.*\\(([0-9.]+)\\).*/\\1/')"
DM_THRESHOLD="$(printf '%s' "$threshold_raw" | sed -E 's/.*\\(([0-9]+)\\).*/\\1/')"

if [[ -z "$DM_BRIGHTNESS" ]]; then DM_BRIGHTNESS="1.0"; fi
if [[ -z "$DM_CONTRAST" ]]; then DM_CONTRAST="1.0"; fi
if [[ -z "$DM_GAMMA" ]]; then DM_GAMMA="1.0"; fi

case "$color_raw" in
  *Monochrome) DM_COLOR_MODE="monochrome" ;;
  *Grayscale) DM_COLOR_MODE="grayscale" ;;
  *TrueColor) DM_COLOR_MODE="truecolor" ;;
  *) DM_COLOR_MODE="truecolor" ;;
esac

{
  echo "# Generated by scripts/dotmax_live_tuner.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Source image: $INPUT_IMAGE"
  echo "# Log: $LOG_FILE"
  echo ""
  echo "DM_DITHER=$DM_DITHER"
  echo "DM_BRIGHTNESS=$DM_BRIGHTNESS"
  echo "DM_CONTRAST=$DM_CONTRAST"
  echo "DM_GAMMA=$DM_GAMMA"
  echo "DM_COLOR_MODE=$DM_COLOR_MODE"
  if [[ -n "$DM_THRESHOLD" ]]; then
    echo "DM_THRESHOLD=$DM_THRESHOLD"
  else
    echo "# DM_THRESHOLD= (auto)"
  fi
  echo ""
  echo "# Apply these + regenerate:"
  echo "# set -a; source $EXPORT_FILE; set +a"
  echo "# ./scripts/generate_dotmax_pieces.sh"
} > "$EXPORT_FILE"

echo "[dotmax-live-tuner] exported final settings -> $EXPORT_FILE"
echo "[dotmax-live-tuner] regenerate with: set -a; source $EXPORT_FILE; set +a; ./scripts/generate_dotmax_pieces.sh"
